version: '3.8'

services:
  # 1. BACKEND service (FastAPI)
  backend:
    image: ghcr.io/dmtschulz/mnist-anomaly-mlops-backend:latest
    container_name: mlops-backend
    restart: always
    build:
      context: . 
      dockerfile: Dockerfile.backend # Указываем, если хотим собирать локально
    ports:
      - "5000:5000" # Внешний и внутренний порты должны совпадать с Dockerfile
    
    # УДАЛЯЕМ HF_CACHE и HF_VARS
    # volumes:
    #   - ./.hf_cache_data:/app/hf_cache
    
    environment:
      # ПЕРЕДАЧА ИМЕНИ S3 БАКЕТА В КОНТЕЙНЕР
      - S3_BUCKET_NAME=anomaly-mlops-mnist-data # Ваше точное имя бакета
      - AWS_REGION=$AWS_REGION # Передаем регион, если нужно для Boto3
      - BACKEND_PORT=5000

  # 2. FRONTEND Service (Streamlit)
  frontend:
    image: ghcr.io/dmtschulz/mnist-anomaly-mlops-frontend:latest
    container_name: mlops-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501" 
    
    depends_on:
      - backend
    
    environment:
      # Streamlit обращается к Backend по имени сервиса (backend:5000)
      - API_HOST=backend
      - API_PORT=5000 # Порт, который слушает Backend контейнер